Language->zh-CN
Version->1.4.0
Layout->0
Expansions->1
Wallpaper->1130001
ETag_1560170458->"e54aaf1775577498ec008aa71ed7bbb8"
ETag_1238056800->W/"4d1430783b40024a53b947f0ff570fe8"
CardLanguage->zh-CN
PrereleaseLanguage->zh-CN
FPS->60000
BgmVol->699
SEVol->699
VoiceVol->699
Scale->1000
AAA->0
Shadow->0
ShowFPS->1
Background->0
MyCardToken->0
DuelFace0->1010001
DuelFace1->1010001
DuelFace0Tag->1010001
DuelFace1Tag->1010001
WatchFace0->1010001
WatchFace1->1010001
WatchFace0Tag->1010001
WatchFace1Tag->1010001
ReplayFace0->1010001
ReplayFace1->1010001
ReplayFace0Tag->1010001
ReplayFace1Tag->1010001
DuelFrame0->1030001
DuelFrame1->1030001
DuelFrame0Tag->1030001
DuelFrame1Tag->1030001
WatchFrame0->1030001
WatchFrame1->1030001
WatchFrame0Tag->1030001
WatchFrame1Tag->1030001
ReplayFrame0->1030001
ReplayFrame1->1030001
ReplayFrame0Tag->1030001
ReplayFrame1Tag->1030001
DuelProtector0->1070001
DuelProtector1->1070001
DuelProtector0Tag->1070001
DuelProtector1Tag->1070001
WatchProtector0->1070001
WatchProtector1->1070001
WatchProtector0Tag->1070001
WatchProtector1Tag->1070001
ReplayProtector0->1070001
ReplayProtector1->1070001
ReplayProtector0Tag->1070001
ReplayProtector1Tag->1070001
DuelCharacter0->0001
WatchCharacter0->0001
ReplayCharacter0->0001
ScreenMode->2
Quality->2000
FAA->1000
Rumble->1
Confirm->0
BGMbyMySide->1
CardStyle->OCG_TCG
VideoCard->1
DuelPlayerName0->@ui
WatchPlayerName0->@ui
ReplayPlayerName0->@ui
DuelVoice->0
WatchVoice->0
ReplayVoice->0
DuelCloseup->0
WatchCloseup->0
ReplayCloseup->0
DuelSummon->1
WatchSummon->1
ReplaySummon->1
DuelPendulum->1
WatchPendulum->1
ReplayPendulum->1
DuelCutin->1
WatchCutin->1
ReplayCutin->1
DuelEffect->1
WatchEffect->1
ReplayEffect->1
DuelChain->1
WatchChain->1
ReplayChain->1
DuelDice->1
WatchDice->1
ReplayDice->1
DuelCoin->1
WatchCoin->1
ReplayCoin->1
DuelAutoInfo->1
WatchAutoInfo->1
ReplayAutoInfo->1
DuelFaceDown->1
WatchFaceDown->1
ReplayFaceDown->1
DuelPlayerMessage->1
WatchPlayerMessage->1
ReplayPlayerMessage->1
DuelSystemMessage->1
WatchSystemMessage->1
ReplaySystemMessage->1
DuelAcc->2000
WatchAcc->2000
ReplayAcc->2000
DuelAutoAcc->1
WatchAutoAcc->1
ReplayAutoAcc->1
Timing->0
AutoRPS->0
Resolution->1600 x 900
DeckInUse->退魔天使エクソシスター
DuelPlayerName1->@ui
DuelField0->1090001
OverrideDeckAppearance->0
DuelField1->1090001
DuelGrave0->1100001
DuelGrave1->1100001
DuelStand0->1110001
DuelStand1->1110001
DuelMate0->1000001
DuelMate1->1000001
MateViewTips->0
UIScale->1000
