using System;

namespace System.Data.Common
{
	/// <summary>Provides the data for the RowUpdating event of a .NET Framework data provider.</summary>
	/// <filterpriority>2</filterpriority>
	// Token: 0x02000107 RID: 263
	public class RowUpdatingEventArgs : EventArgs
	{
		/// <summary>Gets or sets the <see cref="T:System.Data.IDbCommand" /> object for an instance of this class.</summary>
		/// <returns>The <see cref="T:System.Data.IDbCommand" /> to execute during the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />. </returns>
		// Token: 0x17000217 RID: 535
		// (get) Token: 0x06000DC4 RID: 3524 RVA: 0x00046E4A File Offset: 0x0004504A
		// (set) Token: 0x06000DC5 RID: 3525 RVA: 0x00046E52 File Offset: 0x00045052
		protected virtual IDbCommand BaseCommand
		{
			get
			{
				return this._command;
			}
			set
			{
				this._command = value;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.IDbCommand" /> to execute during the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" /> operation.</summary>
		/// <returns>The <see cref="T:System.Data.IDbCommand" /> to execute during the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x17000218 RID: 536
		// (get) Token: 0x06000DC6 RID: 3526 RVA: 0x00046E5B File Offset: 0x0004505B
		// (set) Token: 0x06000DC7 RID: 3527 RVA: 0x00046E63 File Offset: 0x00045063
		public IDbCommand Command
		{
			get
			{
				return this.BaseCommand;
			}
			set
			{
				this.BaseCommand = value;
			}
		}

		/// <summary>Gets any errors generated by the .NET Framework data provider when the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> executes.</summary>
		/// <returns>The errors generated by the .NET Framework data provider when the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> executes.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x17000219 RID: 537
		// (set) Token: 0x06000DC8 RID: 3528 RVA: 0x00046E6C File Offset: 0x0004506C
		public Exception Errors
		{
			set
			{
				this._errors = value;
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.DataRow" /> that will be sent to the server as part of an insert, update, or delete operation.</summary>
		/// <returns>The <see cref="T:System.Data.DataRow" /> to send through an <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x1700021A RID: 538
		// (get) Token: 0x06000DC9 RID: 3529 RVA: 0x00046E75 File Offset: 0x00045075
		public DataRow Row
		{
			get
			{
				return this._dataRow;
			}
		}

		/// <summary>Gets the type of SQL statement to execute.</summary>
		/// <returns>The type of SQL statement to execute.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x1700021B RID: 539
		// (get) Token: 0x06000DCA RID: 3530 RVA: 0x00046E7D File Offset: 0x0004507D
		public StatementType StatementType
		{
			get
			{
				return this._statementType;
			}
		}

		/// <summary>Gets or sets the <see cref="T:System.Data.UpdateStatus" /> of the <see cref="P:System.Data.Common.RowUpdatedEventArgs.Command" /> property.</summary>
		/// <returns>One of the <see cref="T:System.Data.UpdateStatus" /> values. The default is Continue.</returns>
		/// <filterpriority>1</filterpriority>
		/// <PermissionSet>
		///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" PathDiscovery="*AllFiles*" />
		/// </PermissionSet>
		// Token: 0x1700021C RID: 540
		// (get) Token: 0x06000DCB RID: 3531 RVA: 0x00046E85 File Offset: 0x00045085
		// (set) Token: 0x06000DCC RID: 3532 RVA: 0x00046E8D File Offset: 0x0004508D
		public UpdateStatus Status
		{
			get
			{
				return this._status;
			}
			set
			{
				if (value <= UpdateStatus.SkipAllRemainingRows)
				{
					this._status = value;
					return;
				}
				throw ADP.InvalidUpdateStatus(value);
			}
		}

		/// <summary>Gets the <see cref="T:System.Data.Common.DataTableMapping" /> to send through the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</summary>
		/// <returns>The <see cref="T:System.Data.Common.DataTableMapping" /> to send through the <see cref="M:System.Data.Common.DbDataAdapter.Update(System.Data.DataSet)" />.</returns>
		/// <filterpriority>1</filterpriority>
		// Token: 0x1700021D RID: 541
		// (get) Token: 0x06000DCD RID: 3533 RVA: 0x00046EA1 File Offset: 0x000450A1
		public DataTableMapping TableMapping
		{
			get
			{
				return this._tableMapping;
			}
		}

		// Token: 0x0400057B RID: 1403
		private IDbCommand _command;

		// Token: 0x0400057C RID: 1404
		private StatementType _statementType;

		// Token: 0x0400057D RID: 1405
		private DataTableMapping _tableMapping;

		// Token: 0x0400057E RID: 1406
		private Exception _errors;

		// Token: 0x0400057F RID: 1407
		private DataRow _dataRow;

		// Token: 0x04000580 RID: 1408
		private UpdateStatus _status;
	}
}
