using System;

namespace System.Runtime.CompilerServices
{
	/// <summary>Allows you to determine whether a method is a state machine method.</summary>
	// Token: 0x02000596 RID: 1430
	[AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
	[Serializable]
	public class StateMachineAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Runtime.CompilerServices.StateMachineAttribute" /> class.</summary>
		/// <param name="stateMachineType">The type object for the underlying state machine type that was generated by the compiler to implement the state machine method.</param>
		// Token: 0x06002B0A RID: 11018 RVA: 0x000AAC5C File Offset: 0x000A8E5C
		public StateMachineAttribute(Type stateMachineType)
		{
			this.StateMachineType = stateMachineType;
		}

		/// <summary>Returns the type object for the underlying state machine type that was generated by the compiler to implement the state machine method.</summary>
		/// <returns>Gets the type object for the underlying state machine type that was generated by the compiler to implement the state machine method.</returns>
		// Token: 0x1700057D RID: 1405
		// (get) Token: 0x06002B0B RID: 11019 RVA: 0x000AAC6B File Offset: 0x000A8E6B
		public Type StateMachineType { get; }
	}
}
