using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.Playables;

namespace Cinemachine
{
	// Token: 0x020000AB RID: 171
	[DocumentationSorting(DocumentationSortingAttribute.Level.UserRef)]
	[SaveDuringPlay]
	[HelpURL("https://docs.unity3d.com/Packages/com.unity.cinemachine@2.9/api/Cinemachine.CinemachineTriggerAction.html")]
	public class CinemachineTriggerAction : MonoBehaviour
	{
		// Token: 0x060003E9 RID: 1001 RVA: 0x00016B40 File Offset: 0x00014D40
		private bool Filter(GameObject other)
		{
			return base.enabled && ((1 << other.layer) & this.m_LayerMask) != 0 && (this.m_WithTag.Length == 0 || other.CompareTag(this.m_WithTag)) && (this.m_WithoutTag.Length == 0 || !other.CompareTag(this.m_WithoutTag));
		}

		// Token: 0x060003EA RID: 1002 RVA: 0x00016BB0 File Offset: 0x00014DB0
		private void InternalDoTriggerEnter(GameObject other)
		{
			if (!this.Filter(other))
			{
				return;
			}
			this.m_SkipFirst--;
			if (this.m_SkipFirst > -1)
			{
				return;
			}
			if (!this.m_Repeating && this.m_SkipFirst != -1)
			{
				return;
			}
			this.m_ActiveTriggerObjects.Add(other);
			this.m_OnObjectEnter.Invoke();
		}

		// Token: 0x060003EB RID: 1003 RVA: 0x00016C09 File Offset: 0x00014E09
		private void InternalDoTriggerExit(GameObject other)
		{
			if (!this.m_ActiveTriggerObjects.Contains(other))
			{
				return;
			}
			this.m_ActiveTriggerObjects.Remove(other);
			if (base.enabled)
			{
				this.m_OnObjectExit.Invoke();
			}
		}

		// Token: 0x060003EC RID: 1004 RVA: 0x00016C3A File Offset: 0x00014E3A
		private void OnTriggerEnter(Collider other)
		{
			this.InternalDoTriggerEnter(other.gameObject);
		}

		// Token: 0x060003ED RID: 1005 RVA: 0x00016C48 File Offset: 0x00014E48
		private void OnTriggerExit(Collider other)
		{
			this.InternalDoTriggerExit(other.gameObject);
		}

		// Token: 0x060003EE RID: 1006 RVA: 0x00016C56 File Offset: 0x00014E56
		private void OnCollisionEnter(Collision other)
		{
			this.InternalDoTriggerEnter(other.gameObject);
		}

		// Token: 0x060003EF RID: 1007 RVA: 0x00016C64 File Offset: 0x00014E64
		private void OnCollisionExit(Collision other)
		{
			this.InternalDoTriggerExit(other.gameObject);
		}

		// Token: 0x060003F0 RID: 1008 RVA: 0x00016C3A File Offset: 0x00014E3A
		private void OnTriggerEnter2D(Collider2D other)
		{
			this.InternalDoTriggerEnter(other.gameObject);
		}

		// Token: 0x060003F1 RID: 1009 RVA: 0x00016C48 File Offset: 0x00014E48
		private void OnTriggerExit2D(Collider2D other)
		{
			this.InternalDoTriggerExit(other.gameObject);
		}

		// Token: 0x060003F2 RID: 1010 RVA: 0x00016C72 File Offset: 0x00014E72
		private void OnCollisionEnter2D(Collision2D other)
		{
			this.InternalDoTriggerEnter(other.gameObject);
		}

		// Token: 0x060003F3 RID: 1011 RVA: 0x00016C80 File Offset: 0x00014E80
		private void OnCollisionExit2D(Collision2D other)
		{
			this.InternalDoTriggerExit(other.gameObject);
		}

		// Token: 0x060003F4 RID: 1012 RVA: 0x0000429A File Offset: 0x0000249A
		private void OnEnable()
		{
		}

		// Token: 0x0400037E RID: 894
		[Header("Trigger Object Filter")]
		[Tooltip("Only triggers generated by objects on these layers will be considered")]
		public LayerMask m_LayerMask = 1;

		// Token: 0x0400037F RID: 895
		[TagField]
		[Tooltip("If set, only triggers generated by objects with this tag will be considered")]
		public string m_WithTag = string.Empty;

		// Token: 0x04000380 RID: 896
		[TagField]
		[Tooltip("Triggers generated by objects with this tag will be ignored")]
		public string m_WithoutTag = string.Empty;

		// Token: 0x04000381 RID: 897
		[NoSaveDuringPlay]
		[Tooltip("Skip this many trigger entries before taking action")]
		public int m_SkipFirst;

		// Token: 0x04000382 RID: 898
		[Tooltip("Repeat the action for all subsequent trigger entries")]
		public bool m_Repeating = true;

		// Token: 0x04000383 RID: 899
		public CinemachineTriggerAction.ActionSettings m_OnObjectEnter = new CinemachineTriggerAction.ActionSettings(CinemachineTriggerAction.ActionSettings.Mode.Custom);

		// Token: 0x04000384 RID: 900
		public CinemachineTriggerAction.ActionSettings m_OnObjectExit = new CinemachineTriggerAction.ActionSettings(CinemachineTriggerAction.ActionSettings.Mode.Custom);

		// Token: 0x04000385 RID: 901
		private HashSet<GameObject> m_ActiveTriggerObjects = new HashSet<GameObject>();

		// Token: 0x020000AC RID: 172
		[Serializable]
		public struct ActionSettings
		{
			// Token: 0x060003F6 RID: 1014 RVA: 0x00016CEF File Offset: 0x00014EEF
			public ActionSettings(CinemachineTriggerAction.ActionSettings.Mode action)
			{
				this.m_Action = action;
				this.m_Target = null;
				this.m_BoostAmount = 0;
				this.m_StartTime = 0f;
				this.m_Mode = CinemachineTriggerAction.ActionSettings.TimeMode.FromStart;
				this.m_Event = new CinemachineTriggerAction.ActionSettings.TriggerEvent();
			}

			// Token: 0x060003F7 RID: 1015 RVA: 0x00016D24 File Offset: 0x00014F24
			public void Invoke()
			{
				global::UnityEngine.Object currentTarget = this.m_Target;
				if (currentTarget != null)
				{
					GameObject targetGameObject = currentTarget as GameObject;
					Behaviour targetBehaviour = currentTarget as Behaviour;
					if (targetBehaviour != null)
					{
						targetGameObject = targetBehaviour.gameObject;
					}
					switch (this.m_Action)
					{
					case CinemachineTriggerAction.ActionSettings.Mode.PriorityBoost:
					{
						CinemachineVirtualCameraBase vcam = targetGameObject.GetComponent<CinemachineVirtualCameraBase>();
						if (vcam != null)
						{
							vcam.Priority += this.m_BoostAmount;
							vcam.MoveToTopOfPrioritySubqueue();
						}
						break;
					}
					case CinemachineTriggerAction.ActionSettings.Mode.Activate:
						if (targetGameObject != null)
						{
							targetGameObject.SetActive(true);
							CinemachineVirtualCameraBase vcam2 = targetGameObject.GetComponent<CinemachineVirtualCameraBase>();
							if (vcam2 != null)
							{
								vcam2.MoveToTopOfPrioritySubqueue();
							}
						}
						break;
					case CinemachineTriggerAction.ActionSettings.Mode.Deactivate:
						if (targetGameObject != null)
						{
							targetGameObject.SetActive(false);
						}
						break;
					case CinemachineTriggerAction.ActionSettings.Mode.Enable:
						if (targetBehaviour != null)
						{
							targetBehaviour.enabled = true;
						}
						break;
					case CinemachineTriggerAction.ActionSettings.Mode.Disable:
						if (targetBehaviour != null)
						{
							targetBehaviour.enabled = false;
						}
						break;
					case CinemachineTriggerAction.ActionSettings.Mode.Play:
					{
						PlayableDirector playable = targetGameObject.GetComponent<PlayableDirector>();
						if (playable != null)
						{
							double startTime = 0.0;
							double duration = playable.duration;
							double current = playable.time;
							switch (this.m_Mode)
							{
							default:
								startTime += (double)this.m_StartTime;
								break;
							case CinemachineTriggerAction.ActionSettings.TimeMode.FromEnd:
								startTime = duration - (double)this.m_StartTime;
								break;
							case CinemachineTriggerAction.ActionSettings.TimeMode.BeforeNow:
								startTime = current - (double)this.m_StartTime;
								break;
							case CinemachineTriggerAction.ActionSettings.TimeMode.AfterNow:
								startTime = current + (double)this.m_StartTime;
								break;
							}
							playable.time = startTime;
							playable.Play();
						}
						else
						{
							Animation ani = targetGameObject.GetComponent<Animation>();
							if (ani != null)
							{
								ani.Play();
							}
						}
						break;
					}
					case CinemachineTriggerAction.ActionSettings.Mode.Stop:
					{
						PlayableDirector playable2 = targetGameObject.GetComponent<PlayableDirector>();
						if (playable2 != null)
						{
							playable2.Stop();
						}
						else
						{
							Animation ani2 = targetGameObject.GetComponent<Animation>();
							if (ani2 != null)
							{
								ani2.Stop();
							}
						}
						break;
					}
					}
				}
				this.m_Event.Invoke();
			}

			// Token: 0x04000386 RID: 902
			[Tooltip("What action to take")]
			public CinemachineTriggerAction.ActionSettings.Mode m_Action;

			// Token: 0x04000387 RID: 903
			[Tooltip("The target object on which to operate.  If null, then the current behaviour/GameObject will be used")]
			public global::UnityEngine.Object m_Target;

			// Token: 0x04000388 RID: 904
			[Tooltip("If PriorityBoost, this amount will be added to the virtual camera's priority")]
			public int m_BoostAmount;

			// Token: 0x04000389 RID: 905
			[Tooltip("If playing a timeline, start at this time")]
			public float m_StartTime;

			// Token: 0x0400038A RID: 906
			[Tooltip("How to interpret the start time")]
			public CinemachineTriggerAction.ActionSettings.TimeMode m_Mode;

			// Token: 0x0400038B RID: 907
			[Tooltip("This event will be invoked")]
			public CinemachineTriggerAction.ActionSettings.TriggerEvent m_Event;

			// Token: 0x020000AD RID: 173
			public enum Mode
			{
				// Token: 0x0400038D RID: 909
				Custom,
				// Token: 0x0400038E RID: 910
				PriorityBoost,
				// Token: 0x0400038F RID: 911
				Activate,
				// Token: 0x04000390 RID: 912
				Deactivate,
				// Token: 0x04000391 RID: 913
				Enable,
				// Token: 0x04000392 RID: 914
				Disable,
				// Token: 0x04000393 RID: 915
				Play,
				// Token: 0x04000394 RID: 916
				Stop
			}

			// Token: 0x020000AE RID: 174
			[Serializable]
			public class TriggerEvent : UnityEvent
			{
			}

			// Token: 0x020000AF RID: 175
			public enum TimeMode
			{
				// Token: 0x04000396 RID: 918
				FromStart,
				// Token: 0x04000397 RID: 919
				FromEnd,
				// Token: 0x04000398 RID: 920
				BeforeNow,
				// Token: 0x04000399 RID: 921
				AfterNow
			}
		}
	}
}
