using System;
using System.CodeDom;
using System.Collections.Specialized;
using System.Xml.Schema;

namespace System.Xml.Serialization.Advanced
{
	// Token: 0x020001FF RID: 511
	internal class MappedTypeDesc
	{
		// Token: 0x060019D0 RID: 6608 RVA: 0x000979B8 File Offset: 0x00095BB8
		internal MappedTypeDesc(string clrType, string name, string ns, XmlSchemaType xsdType, XmlSchemaObject context, SchemaImporterExtension extension, CodeNamespace code, StringCollection references)
		{
			this.clrType = clrType.Replace('+', '.');
			this.name = name;
			this.ns = ns;
			this.xsdType = xsdType;
			this.context = context;
			this.code = code;
			this.references = references;
			this.extension = extension;
		}

		// Token: 0x170005BC RID: 1468
		// (get) Token: 0x060019D1 RID: 6609 RVA: 0x00097A11 File Offset: 0x00095C11
		internal SchemaImporterExtension Extension
		{
			get
			{
				return this.extension;
			}
		}

		// Token: 0x170005BD RID: 1469
		// (get) Token: 0x060019D2 RID: 6610 RVA: 0x00097A19 File Offset: 0x00095C19
		internal string Name
		{
			get
			{
				return this.clrType;
			}
		}

		// Token: 0x170005BE RID: 1470
		// (get) Token: 0x060019D3 RID: 6611 RVA: 0x00097A21 File Offset: 0x00095C21
		internal StringCollection ReferencedAssemblies
		{
			get
			{
				if (this.references == null)
				{
					this.references = new StringCollection();
				}
				return this.references;
			}
		}

		// Token: 0x060019D4 RID: 6612 RVA: 0x00097A3C File Offset: 0x00095C3C
		internal CodeTypeDeclaration ExportTypeDefinition(CodeNamespace codeNamespace, CodeCompileUnit codeCompileUnit)
		{
			if (this.exported)
			{
				return null;
			}
			this.exported = true;
			foreach (object obj in this.code.Imports)
			{
				CodeNamespaceImport codeNamespaceImport = (CodeNamespaceImport)obj;
				codeNamespace.Imports.Add(codeNamespaceImport);
			}
			CodeTypeDeclaration codeTypeDeclaration = null;
			string @string = Res.GetString("This type definition was generated by {0} schema importer extension.", new object[] { this.extension.GetType().FullName });
			foreach (object obj2 in this.code.Types)
			{
				CodeTypeDeclaration codeTypeDeclaration2 = (CodeTypeDeclaration)obj2;
				if (this.clrType == codeTypeDeclaration2.Name)
				{
					if (codeTypeDeclaration != null)
					{
						throw new InvalidOperationException(Res.GetString("Schema importer extension {0} generated duplicate type definitions: {1}.", new object[]
						{
							this.extension.GetType().FullName,
							this.clrType
						}));
					}
					codeTypeDeclaration = codeTypeDeclaration2;
				}
				codeTypeDeclaration2.Comments.Add(new CodeCommentStatement(@string, false));
				codeNamespace.Types.Add(codeTypeDeclaration2);
			}
			if (codeCompileUnit != null)
			{
				foreach (string text in this.ReferencedAssemblies)
				{
					if (!codeCompileUnit.ReferencedAssemblies.Contains(text))
					{
						codeCompileUnit.ReferencedAssemblies.Add(text);
					}
				}
			}
			return codeTypeDeclaration;
		}

		// Token: 0x04000AF4 RID: 2804
		private string name;

		// Token: 0x04000AF5 RID: 2805
		private string ns;

		// Token: 0x04000AF6 RID: 2806
		private XmlSchemaType xsdType;

		// Token: 0x04000AF7 RID: 2807
		private XmlSchemaObject context;

		// Token: 0x04000AF8 RID: 2808
		private string clrType;

		// Token: 0x04000AF9 RID: 2809
		private SchemaImporterExtension extension;

		// Token: 0x04000AFA RID: 2810
		private CodeNamespace code;

		// Token: 0x04000AFB RID: 2811
		private bool exported;

		// Token: 0x04000AFC RID: 2812
		private StringCollection references;
	}
}
