using System;
using System.Collections;
using System.Globalization;

namespace System.Xml.Serialization
{
	/// <summary>Maintains a group of names for related code entities or type mappings that are generated by the .NET Framework's XML serialization infrastructure.</summary>
	// Token: 0x02000150 RID: 336
	public class CodeIdentifiers
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> class. </summary>
		// Token: 0x06001099 RID: 4249 RVA: 0x0005114B File Offset: 0x0004F34B
		public CodeIdentifiers()
			: this(true)
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> class and determines whether code identifiers are case sensitive.</summary>
		/// <param name="caseSensitive">true if identifiers are case sensitive; otherwise, false. </param>
		// Token: 0x0600109A RID: 4250 RVA: 0x00051154 File Offset: 0x0004F354
		public CodeIdentifiers(bool caseSensitive)
		{
			if (caseSensitive)
			{
				this.identifiers = new Hashtable();
				this.reservedIdentifiers = new Hashtable();
			}
			else
			{
				IEqualityComparer equalityComparer = new CaseInsensitiveKeyComparer();
				this.identifiers = new Hashtable(equalityComparer);
				this.reservedIdentifiers = new Hashtable(equalityComparer);
			}
			this.list = new ArrayList();
		}

		/// <summary>Removes all code entities or type mappings, including their names, from the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope. </summary>
		// Token: 0x0600109B RID: 4251 RVA: 0x000511AB File Offset: 0x0004F3AB
		public void Clear()
		{
			this.identifiers.Clear();
			this.list.Clear();
		}

		/// <summary>Gets or sets a value that indicates whether the instance uses camel case. </summary>
		/// <returns>true to indicate that the instance uses camel case; false to indicate that the instance uses Pascal case.</returns>
		// Token: 0x170003B5 RID: 949
		// (get) Token: 0x0600109C RID: 4252 RVA: 0x000511C3 File Offset: 0x0004F3C3
		// (set) Token: 0x0600109D RID: 4253 RVA: 0x000511CB File Offset: 0x0004F3CB
		public bool UseCamelCasing
		{
			get
			{
				return this.camelCase;
			}
			set
			{
				this.camelCase = value;
			}
		}

		/// <summary>Ensures that the input is of the correct case by modifying the name according to the value of the <see cref="P:System.Xml.Serialization.CodeIdentifiers.UseCamelCasing" /> property. </summary>
		/// <returns>A string that is the same as the input identifier or has the first letter's case modified.</returns>
		/// <param name="identifier">The name to possibly modify.</param>
		// Token: 0x0600109E RID: 4254 RVA: 0x000511D4 File Offset: 0x0004F3D4
		public string MakeRightCase(string identifier)
		{
			if (this.camelCase)
			{
				return CodeIdentifier.MakeCamel(identifier);
			}
			return CodeIdentifier.MakePascal(identifier);
		}

		/// <summary>Determines whether the input name conflicts with another name within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope and, if it does, generates a modified string. </summary>
		/// <returns>The identifier parameter value or a modified string if there is a name collision.</returns>
		/// <param name="identifier">The name to modify if it is not already unique.</param>
		// Token: 0x0600109F RID: 4255 RVA: 0x000511EC File Offset: 0x0004F3EC
		public string MakeUnique(string identifier)
		{
			if (this.IsInUse(identifier))
			{
				int num = 1;
				string text;
				for (;;)
				{
					text = identifier + num.ToString(CultureInfo.InvariantCulture);
					if (!this.IsInUse(text))
					{
						break;
					}
					num++;
				}
				identifier = text;
			}
			if (identifier.Length > 511)
			{
				return this.MakeUnique("Item");
			}
			return identifier;
		}

		/// <summary>Prevents a specified name from being used within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope. </summary>
		/// <param name="identifier">A name that will not be available within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" />instance's scope.</param>
		// Token: 0x060010A0 RID: 4256 RVA: 0x00051245 File Offset: 0x0004F445
		public void AddReserved(string identifier)
		{
			this.reservedIdentifiers.Add(identifier, identifier);
		}

		/// <summary>Removes the input name from the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's reserved names. </summary>
		/// <param name="identifier">A name that will be made available within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope.</param>
		// Token: 0x060010A1 RID: 4257 RVA: 0x00051254 File Offset: 0x0004F454
		public void RemoveReserved(string identifier)
		{
			this.reservedIdentifiers.Remove(identifier);
		}

		/// <summary>Adds a named code entity or type mapping to the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope, ensuring that the name is unique within the scope. </summary>
		/// <returns>The identifier parameter value or a modified string if there is a name collision.</returns>
		/// <param name="identifier">A candidate name that is used to index the code entity.</param>
		/// <param name="value">The code entity or type mapping information.</param>
		// Token: 0x060010A2 RID: 4258 RVA: 0x00051262 File Offset: 0x0004F462
		public string AddUnique(string identifier, object value)
		{
			identifier = this.MakeUnique(identifier);
			this.Add(identifier, value);
			return identifier;
		}

		/// <summary>Determines whether a specified name is already being used within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope. </summary>
		/// <returns>true if the name is already in use; otherwise, false.</returns>
		/// <param name="identifier">The name to check for use within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope.</param>
		// Token: 0x060010A3 RID: 4259 RVA: 0x00051276 File Offset: 0x0004F476
		public bool IsInUse(string identifier)
		{
			return this.identifiers.Contains(identifier) || this.reservedIdentifiers.Contains(identifier);
		}

		/// <summary>Adds a named code entity or type mapping to the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope. </summary>
		/// <param name="identifier">A name that is used to index the code entity.</param>
		/// <param name="value">The code entity or type mapping information.</param>
		// Token: 0x060010A4 RID: 4260 RVA: 0x00051294 File Offset: 0x0004F494
		public void Add(string identifier, object value)
		{
			this.identifiers.Add(identifier, value);
			this.list.Add(value);
		}

		/// <summary>Removes from the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope the code entity or type mapping identified by the input name. </summary>
		/// <param name="identifier">The name of the code entity or type mapping information to remove.</param>
		// Token: 0x060010A5 RID: 4261 RVA: 0x000512B0 File Offset: 0x0004F4B0
		public void Remove(string identifier)
		{
			this.list.Remove(this.identifiers[identifier]);
			this.identifiers.Remove(identifier);
		}

		/// <summary>Returns an array of the code entities or type mappings within the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> instance's scope. </summary>
		/// <returns>An array of the code entities or type mappings that is stored by the <see cref="T:System.Xml.Serialization.CodeIdentifiers" /> object.</returns>
		/// <param name="type">The type of all the code entities or type mappings for the instance.</param>
		// Token: 0x060010A6 RID: 4262 RVA: 0x000512D8 File Offset: 0x0004F4D8
		public object ToArray(Type type)
		{
			Array array = Array.CreateInstance(type, this.list.Count);
			this.list.CopyTo(array, 0);
			return array;
		}

		// Token: 0x060010A7 RID: 4263 RVA: 0x00051308 File Offset: 0x0004F508
		internal CodeIdentifiers Clone()
		{
			return new CodeIdentifiers
			{
				identifiers = (Hashtable)this.identifiers.Clone(),
				reservedIdentifiers = (Hashtable)this.reservedIdentifiers.Clone(),
				list = (ArrayList)this.list.Clone(),
				camelCase = this.camelCase
			};
		}

		// Token: 0x04000803 RID: 2051
		private Hashtable identifiers;

		// Token: 0x04000804 RID: 2052
		private Hashtable reservedIdentifiers;

		// Token: 0x04000805 RID: 2053
		private ArrayList list;

		// Token: 0x04000806 RID: 2054
		private bool camelCase;
	}
}
