using System;

namespace System.Xml.Serialization
{
	/// <summary>Controls the schema generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" /> when a class instance is serialized as SOAP encoded XML.</summary>
	// Token: 0x02000194 RID: 404
	[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Interface)]
	public class SoapTypeAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapTypeAttribute" /> class.</summary>
		// Token: 0x06001324 RID: 4900 RVA: 0x0005DF48 File Offset: 0x0005C148
		public SoapTypeAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapTypeAttribute" /> class and specifies the name of the XML type.</summary>
		/// <param name="typeName">The name of the XML type that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates when it serializes the class instance (and recognizes when it deserializes the class instance). </param>
		// Token: 0x06001325 RID: 4901 RVA: 0x0005DF57 File Offset: 0x0005C157
		public SoapTypeAttribute(string typeName)
		{
			this.typeName = typeName;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapTypeAttribute" /> class and specifies the name and XML namespace of the type.</summary>
		/// <param name="typeName">The name of the XML type that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates when it serializes the class instance (and recognizes when it deserializes the class instance). </param>
		/// <param name="ns">The XML namespace of the type. </param>
		// Token: 0x06001326 RID: 4902 RVA: 0x0005DF6D File Offset: 0x0005C16D
		public SoapTypeAttribute(string typeName, string ns)
		{
			this.typeName = typeName;
			this.ns = ns;
		}

		/// <summary>Gets or sets a value that indicates whether to include the type in SOAP-encoded XML Schema documents.</summary>
		/// <returns>true to include the type in SOAP-encoded XML Schema documents; otherwise, false. The default is true.</returns>
		// Token: 0x17000463 RID: 1123
		// (get) Token: 0x06001327 RID: 4903 RVA: 0x0005DF8A File Offset: 0x0005C18A
		// (set) Token: 0x06001328 RID: 4904 RVA: 0x0005DF92 File Offset: 0x0005C192
		public bool IncludeInSchema
		{
			get
			{
				return this.includeInSchema;
			}
			set
			{
				this.includeInSchema = value;
			}
		}

		/// <summary>Gets or sets the name of the XML type.</summary>
		/// <returns>The name of the XML type. The default is the class name.</returns>
		// Token: 0x17000464 RID: 1124
		// (get) Token: 0x06001329 RID: 4905 RVA: 0x0005DF9B File Offset: 0x0005C19B
		// (set) Token: 0x0600132A RID: 4906 RVA: 0x0005DFB1 File Offset: 0x0005C1B1
		public string TypeName
		{
			get
			{
				if (this.typeName != null)
				{
					return this.typeName;
				}
				return string.Empty;
			}
			set
			{
				this.typeName = value;
			}
		}

		/// <summary>Gets or sets the namespace of the XML type.</summary>
		/// <returns>The namespace of the XML type. The default is an empty string ("").</returns>
		// Token: 0x17000465 RID: 1125
		// (get) Token: 0x0600132B RID: 4907 RVA: 0x0005DFBA File Offset: 0x0005C1BA
		// (set) Token: 0x0600132C RID: 4908 RVA: 0x0005DFC2 File Offset: 0x0005C1C2
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		// Token: 0x040008E1 RID: 2273
		private string ns;

		// Token: 0x040008E2 RID: 2274
		private string typeName;

		// Token: 0x040008E3 RID: 2275
		private bool includeInSchema = true;
	}
}
