using System;

namespace System.Xml.Serialization
{
	/// <summary>Specifies that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> must serialize the class member as an encoded SOAP attribute.</summary>
	// Token: 0x02000187 RID: 391
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue)]
	public class SoapAttributeAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapAttributeAttribute" /> class.</summary>
		// Token: 0x06001285 RID: 4741 RVA: 0x0005995F File Offset: 0x00057B5F
		public SoapAttributeAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.SoapAttributeAttribute" /> class using the specified value as the name of the XML attribute.</summary>
		/// <param name="attributeName">The name of the XML attribute. </param>
		// Token: 0x06001286 RID: 4742 RVA: 0x00059967 File Offset: 0x00057B67
		public SoapAttributeAttribute(string attributeName)
		{
			this.attributeName = attributeName;
		}

		/// <summary>Gets or sets the name of the XML attribute generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>The name of the XML attribute. The default is the member identifier.</returns>
		// Token: 0x1700044F RID: 1103
		// (get) Token: 0x06001287 RID: 4743 RVA: 0x00059976 File Offset: 0x00057B76
		// (set) Token: 0x06001288 RID: 4744 RVA: 0x0005998C File Offset: 0x00057B8C
		public string AttributeName
		{
			get
			{
				if (this.attributeName != null)
				{
					return this.attributeName;
				}
				return string.Empty;
			}
			set
			{
				this.attributeName = value;
			}
		}

		/// <summary>Gets or sets the XML namespace of the XML attribute.</summary>
		/// <returns>The XML namespace of the XML attribute.</returns>
		// Token: 0x17000450 RID: 1104
		// (get) Token: 0x06001289 RID: 4745 RVA: 0x00059995 File Offset: 0x00057B95
		// (set) Token: 0x0600128A RID: 4746 RVA: 0x0005999D File Offset: 0x00057B9D
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		/// <summary>Gets or sets the XML Schema definition language (XSD) data type of the SOAP attribute generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>An XML Schema data type, as defined by the World Wide Web Consortium (www.w3.org) document named "XML Schema Part 2: Datatypes".</returns>
		/// <exception cref="T:System.Exception">The XML Schema data type you have specified cannot be mapped to the .NET data type. </exception>
		// Token: 0x17000451 RID: 1105
		// (get) Token: 0x0600128B RID: 4747 RVA: 0x000599A6 File Offset: 0x00057BA6
		// (set) Token: 0x0600128C RID: 4748 RVA: 0x000599BC File Offset: 0x00057BBC
		public string DataType
		{
			get
			{
				if (this.dataType != null)
				{
					return this.dataType;
				}
				return string.Empty;
			}
			set
			{
				this.dataType = value;
			}
		}

		// Token: 0x040008BC RID: 2236
		private string attributeName;

		// Token: 0x040008BD RID: 2237
		private string ns;

		// Token: 0x040008BE RID: 2238
		private string dataType;
	}
}
