using System;
using System.Xml.Schema;

namespace System.Xml.Serialization
{
	/// <summary>Specifies that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> must serialize a particular class member as an array of XML elements.</summary>
	// Token: 0x020001A3 RID: 419
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue, AllowMultiple = false)]
	public class XmlArrayAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlArrayAttribute" /> class.</summary>
		// Token: 0x060013BF RID: 5055 RVA: 0x00060CB8 File Offset: 0x0005EEB8
		public XmlArrayAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlArrayAttribute" /> class and specifies the XML element name generated in the XML document instance.</summary>
		/// <param name="elementName">The name of the XML element that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates. </param>
		// Token: 0x060013C0 RID: 5056 RVA: 0x00060CC7 File Offset: 0x0005EEC7
		public XmlArrayAttribute(string elementName)
		{
			this.elementName = elementName;
		}

		/// <summary>Gets or sets the XML element name given to the serialized array.</summary>
		/// <returns>The XML element name of the serialized array. The default is the name of the member to which the <see cref="T:System.Xml.Serialization.XmlArrayAttribute" /> is assigned.</returns>
		// Token: 0x1700049E RID: 1182
		// (get) Token: 0x060013C1 RID: 5057 RVA: 0x00060CDD File Offset: 0x0005EEDD
		// (set) Token: 0x060013C2 RID: 5058 RVA: 0x00060CF3 File Offset: 0x0005EEF3
		public string ElementName
		{
			get
			{
				if (this.elementName != null)
				{
					return this.elementName;
				}
				return string.Empty;
			}
			set
			{
				this.elementName = value;
			}
		}

		/// <summary>Gets or sets the namespace of the XML element.</summary>
		/// <returns>The namespace of the XML element.</returns>
		// Token: 0x1700049F RID: 1183
		// (get) Token: 0x060013C3 RID: 5059 RVA: 0x00060CFC File Offset: 0x0005EEFC
		// (set) Token: 0x060013C4 RID: 5060 RVA: 0x00060D04 File Offset: 0x0005EF04
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the <see cref="T:System.Xml.Serialization.XmlSerializer" /> must serialize a member as an empty XML tag with the xsi:nil attribute set to true.</summary>
		/// <returns>true if the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates the xsi:nil attribute; otherwise, false.</returns>
		// Token: 0x170004A0 RID: 1184
		// (get) Token: 0x060013C5 RID: 5061 RVA: 0x00060D0D File Offset: 0x0005EF0D
		// (set) Token: 0x060013C6 RID: 5062 RVA: 0x00060D15 File Offset: 0x0005EF15
		public bool IsNullable
		{
			get
			{
				return this.nullable;
			}
			set
			{
				this.nullable = value;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the XML element name generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" /> is qualified or unqualified.</summary>
		/// <returns>One of the <see cref="T:System.Xml.Schema.XmlSchemaForm" /> values. The default is XmlSchemaForm.None.</returns>
		// Token: 0x170004A1 RID: 1185
		// (get) Token: 0x060013C7 RID: 5063 RVA: 0x00060D1E File Offset: 0x0005EF1E
		// (set) Token: 0x060013C8 RID: 5064 RVA: 0x00060D26 File Offset: 0x0005EF26
		public XmlSchemaForm Form
		{
			get
			{
				return this.form;
			}
			set
			{
				this.form = value;
			}
		}

		/// <summary>Gets or sets the explicit order in which the elements are serialized or deserialized.</summary>
		/// <returns>The order of the code generation.</returns>
		// Token: 0x170004A2 RID: 1186
		// (get) Token: 0x060013C9 RID: 5065 RVA: 0x00060D2F File Offset: 0x0005EF2F
		// (set) Token: 0x060013CA RID: 5066 RVA: 0x00060D37 File Offset: 0x0005EF37
		public int Order
		{
			get
			{
				return this.order;
			}
			set
			{
				if (value < 0)
				{
					throw new ArgumentException(Res.GetString("Negative values are prohibited."), "Order");
				}
				this.order = value;
			}
		}

		// Token: 0x04000936 RID: 2358
		private string elementName;

		// Token: 0x04000937 RID: 2359
		private string ns;

		// Token: 0x04000938 RID: 2360
		private bool nullable;

		// Token: 0x04000939 RID: 2361
		private XmlSchemaForm form;

		// Token: 0x0400093A RID: 2362
		private int order = -1;
	}
}
