using System;
using System.Xml.Schema;

namespace System.Xml.Serialization
{
	/// <summary>Specifies that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> must serialize the class member as an XML attribute.</summary>
	// Token: 0x020001A6 RID: 422
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue)]
	public class XmlAttributeAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlAttributeAttribute" /> class.</summary>
		// Token: 0x060013E7 RID: 5095 RVA: 0x0005995F File Offset: 0x00057B5F
		public XmlAttributeAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlAttributeAttribute" /> class and specifies the name of the generated XML attribute.</summary>
		/// <param name="attributeName">The name of the XML attribute that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates. </param>
		// Token: 0x060013E8 RID: 5096 RVA: 0x00060E42 File Offset: 0x0005F042
		public XmlAttributeAttribute(string attributeName)
		{
			this.attributeName = attributeName;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlAttributeAttribute" /> class.</summary>
		/// <param name="type">The <see cref="T:System.Type" /> used to store the attribute. </param>
		// Token: 0x060013E9 RID: 5097 RVA: 0x00060E51 File Offset: 0x0005F051
		public XmlAttributeAttribute(Type type)
		{
			this.type = type;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlAttributeAttribute" /> class.</summary>
		/// <param name="attributeName">The name of the XML attribute that is generated. </param>
		/// <param name="type">The <see cref="T:System.Type" /> used to store the attribute. </param>
		// Token: 0x060013EA RID: 5098 RVA: 0x00060E60 File Offset: 0x0005F060
		public XmlAttributeAttribute(string attributeName, Type type)
		{
			this.attributeName = attributeName;
			this.type = type;
		}

		/// <summary>Gets or sets the complex type of the XML attribute.</summary>
		/// <returns>The type of the XML attribute.</returns>
		// Token: 0x170004AC RID: 1196
		// (get) Token: 0x060013EB RID: 5099 RVA: 0x00060E76 File Offset: 0x0005F076
		// (set) Token: 0x060013EC RID: 5100 RVA: 0x00060E7E File Offset: 0x0005F07E
		public Type Type
		{
			get
			{
				return this.type;
			}
			set
			{
				this.type = value;
			}
		}

		/// <summary>Gets or sets the name of the XML attribute.</summary>
		/// <returns>The name of the XML attribute. The default is the member name.</returns>
		// Token: 0x170004AD RID: 1197
		// (get) Token: 0x060013ED RID: 5101 RVA: 0x00060E87 File Offset: 0x0005F087
		// (set) Token: 0x060013EE RID: 5102 RVA: 0x00060E9D File Offset: 0x0005F09D
		public string AttributeName
		{
			get
			{
				if (this.attributeName != null)
				{
					return this.attributeName;
				}
				return string.Empty;
			}
			set
			{
				this.attributeName = value;
			}
		}

		/// <summary>Gets or sets the XML namespace of the XML attribute.</summary>
		/// <returns>The XML namespace of the XML attribute.</returns>
		// Token: 0x170004AE RID: 1198
		// (get) Token: 0x060013EF RID: 5103 RVA: 0x00060EA6 File Offset: 0x0005F0A6
		// (set) Token: 0x060013F0 RID: 5104 RVA: 0x00060EAE File Offset: 0x0005F0AE
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		/// <summary>Gets or sets the XSD data type of the XML attribute generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>An XSD (XML Schema Document) data type, as defined by the World Wide Web Consortium (www.w3.org) document named "XML Schema: DataTypes".</returns>
		// Token: 0x170004AF RID: 1199
		// (get) Token: 0x060013F1 RID: 5105 RVA: 0x00060EB7 File Offset: 0x0005F0B7
		// (set) Token: 0x060013F2 RID: 5106 RVA: 0x00060ECD File Offset: 0x0005F0CD
		public string DataType
		{
			get
			{
				if (this.dataType != null)
				{
					return this.dataType;
				}
				return string.Empty;
			}
			set
			{
				this.dataType = value;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the XML attribute name generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" /> is qualified.</summary>
		/// <returns>One of the <see cref="T:System.Xml.Schema.XmlSchemaForm" /> values. The default is XmlForm.None.</returns>
		// Token: 0x170004B0 RID: 1200
		// (get) Token: 0x060013F3 RID: 5107 RVA: 0x00060ED6 File Offset: 0x0005F0D6
		// (set) Token: 0x060013F4 RID: 5108 RVA: 0x00060EDE File Offset: 0x0005F0DE
		public XmlSchemaForm Form
		{
			get
			{
				return this.form;
			}
			set
			{
				this.form = value;
			}
		}

		// Token: 0x04000943 RID: 2371
		private string attributeName;

		// Token: 0x04000944 RID: 2372
		private Type type;

		// Token: 0x04000945 RID: 2373
		private string ns;

		// Token: 0x04000946 RID: 2374
		private string dataType;

		// Token: 0x04000947 RID: 2375
		private XmlSchemaForm form;
	}
}
