using System;
using System.Xml.Schema;

namespace System.Xml.Serialization
{
	/// <summary>Indicates that a public field or property represents an XML element when the <see cref="T:System.Xml.Serialization.XmlSerializer" /> serializes or deserializes the object that contains it.</summary>
	// Token: 0x020001AD RID: 429
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue, AllowMultiple = true)]
	public class XmlElementAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> class.</summary>
		// Token: 0x060014A9 RID: 5289 RVA: 0x00063D10 File Offset: 0x00061F10
		public XmlElementAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> class and specifies the name of the XML element.</summary>
		/// <param name="elementName">The XML element name of the serialized member. </param>
		// Token: 0x060014AA RID: 5290 RVA: 0x00063D1F File Offset: 0x00061F1F
		public XmlElementAttribute(string elementName)
		{
			this.elementName = elementName;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> class and specifies a type for the member to which the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> is applied. This type is used by the <see cref="T:System.Xml.Serialization.XmlSerializer" /> when serializing or deserializing object that contains it.</summary>
		/// <param name="type">The <see cref="T:System.Type" /> of an object derived from the member's type. </param>
		// Token: 0x060014AB RID: 5291 RVA: 0x00063D35 File Offset: 0x00061F35
		public XmlElementAttribute(Type type)
		{
			this.type = type;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> and specifies the name of the XML element and a derived type for the member to which the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> is applied. This member type is used when the <see cref="T:System.Xml.Serialization.XmlSerializer" /> serializes the object that contains it.</summary>
		/// <param name="elementName">The XML element name of the serialized member. </param>
		/// <param name="type">The <see cref="T:System.Type" /> of an object derived from the member's type. </param>
		// Token: 0x060014AC RID: 5292 RVA: 0x00063D4B File Offset: 0x00061F4B
		public XmlElementAttribute(string elementName, Type type)
		{
			this.elementName = elementName;
			this.type = type;
		}

		/// <summary>Gets or sets the object type used to represent the XML element.</summary>
		/// <returns>The <see cref="T:System.Type" /> of the member.</returns>
		// Token: 0x170004E6 RID: 1254
		// (get) Token: 0x060014AD RID: 5293 RVA: 0x00063D68 File Offset: 0x00061F68
		// (set) Token: 0x060014AE RID: 5294 RVA: 0x00063D70 File Offset: 0x00061F70
		public Type Type
		{
			get
			{
				return this.type;
			}
			set
			{
				this.type = value;
			}
		}

		/// <summary>Gets or sets the name of the generated XML element.</summary>
		/// <returns>The name of the generated XML element. The default is the member identifier.</returns>
		// Token: 0x170004E7 RID: 1255
		// (get) Token: 0x060014AF RID: 5295 RVA: 0x00063D79 File Offset: 0x00061F79
		// (set) Token: 0x060014B0 RID: 5296 RVA: 0x00063D8F File Offset: 0x00061F8F
		public string ElementName
		{
			get
			{
				if (this.elementName != null)
				{
					return this.elementName;
				}
				return string.Empty;
			}
			set
			{
				this.elementName = value;
			}
		}

		/// <summary>Gets or sets the namespace assigned to the XML element that results when the class is serialized.</summary>
		/// <returns>The namespace of the XML element.</returns>
		// Token: 0x170004E8 RID: 1256
		// (get) Token: 0x060014B1 RID: 5297 RVA: 0x00063D98 File Offset: 0x00061F98
		// (set) Token: 0x060014B2 RID: 5298 RVA: 0x00063DA0 File Offset: 0x00061FA0
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		/// <summary>Gets or sets the XML Schema definition (XSD) data type of the XML element generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>An XML Schema data type, as defined by the World Wide Web Consortium (www.w3.org) document named "XML Schema Part 2: Datatypes".</returns>
		/// <exception cref="T:System.Exception">The XML Schema data type you have specified cannot be mapped to the.NET data type. </exception>
		// Token: 0x170004E9 RID: 1257
		// (get) Token: 0x060014B3 RID: 5299 RVA: 0x00063DA9 File Offset: 0x00061FA9
		// (set) Token: 0x060014B4 RID: 5300 RVA: 0x00063DBF File Offset: 0x00061FBF
		public string DataType
		{
			get
			{
				if (this.dataType != null)
				{
					return this.dataType;
				}
				return string.Empty;
			}
			set
			{
				this.dataType = value;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the <see cref="T:System.Xml.Serialization.XmlSerializer" /> must serialize a member that is set to null as an empty tag with the xsi:nil attribute set to true.</summary>
		/// <returns>true if the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates the xsi:nil attribute; otherwise, false.</returns>
		// Token: 0x170004EA RID: 1258
		// (get) Token: 0x060014B5 RID: 5301 RVA: 0x00063DC8 File Offset: 0x00061FC8
		// (set) Token: 0x060014B6 RID: 5302 RVA: 0x00063DD0 File Offset: 0x00061FD0
		public bool IsNullable
		{
			get
			{
				return this.nullable;
			}
			set
			{
				this.nullable = value;
				this.nullableSpecified = true;
			}
		}

		// Token: 0x170004EB RID: 1259
		// (get) Token: 0x060014B7 RID: 5303 RVA: 0x00063DE0 File Offset: 0x00061FE0
		internal bool IsNullableSpecified
		{
			get
			{
				return this.nullableSpecified;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the element is qualified.</summary>
		/// <returns>One of the <see cref="T:System.Xml.Schema.XmlSchemaForm" /> values. The default is <see cref="F:System.Xml.Schema.XmlSchemaForm.None" />.</returns>
		// Token: 0x170004EC RID: 1260
		// (get) Token: 0x060014B8 RID: 5304 RVA: 0x00063DE8 File Offset: 0x00061FE8
		// (set) Token: 0x060014B9 RID: 5305 RVA: 0x00063DF0 File Offset: 0x00061FF0
		public XmlSchemaForm Form
		{
			get
			{
				return this.form;
			}
			set
			{
				this.form = value;
			}
		}

		/// <summary>Gets or sets the explicit order in which the elements are serialized or deserialized.</summary>
		/// <returns>The order of the code generation.</returns>
		// Token: 0x170004ED RID: 1261
		// (get) Token: 0x060014BA RID: 5306 RVA: 0x00063DF9 File Offset: 0x00061FF9
		// (set) Token: 0x060014BB RID: 5307 RVA: 0x00063E01 File Offset: 0x00062001
		public int Order
		{
			get
			{
				return this.order;
			}
			set
			{
				if (value < 0)
				{
					throw new ArgumentException(Res.GetString("Negative values are prohibited."), "Order");
				}
				this.order = value;
			}
		}

		// Token: 0x04000969 RID: 2409
		private string elementName;

		// Token: 0x0400096A RID: 2410
		private Type type;

		// Token: 0x0400096B RID: 2411
		private string ns;

		// Token: 0x0400096C RID: 2412
		private string dataType;

		// Token: 0x0400096D RID: 2413
		private bool nullable;

		// Token: 0x0400096E RID: 2414
		private bool nullableSpecified;

		// Token: 0x0400096F RID: 2415
		private XmlSchemaForm form;

		// Token: 0x04000970 RID: 2416
		private int order = -1;
	}
}
