using System;

namespace System.Xml.Serialization
{
	/// <summary>Signifies that the code was generated by the serialization infrastructure and can be reused for increased performance, when this attribute is applied to an assembly.</summary>
	// Token: 0x020001E4 RID: 484
	[AttributeUsage(AttributeTargets.Assembly)]
	public sealed class XmlSerializerVersionAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlSerializerVersionAttribute" /> class. </summary>
		// Token: 0x06001910 RID: 6416 RVA: 0x0005995F File Offset: 0x00057B5F
		public XmlSerializerVersionAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlSerializerVersionAttribute" /> class for the specified type.</summary>
		/// <param name="type">The type that is being serialized.</param>
		// Token: 0x06001911 RID: 6417 RVA: 0x00096264 File Offset: 0x00094464
		public XmlSerializerVersionAttribute(Type type)
		{
			this.type = type;
		}

		/// <summary>Gets or sets the identity of the parent assembly.</summary>
		/// <returns>The version of the parent assembly.</returns>
		// Token: 0x17000580 RID: 1408
		// (get) Token: 0x06001912 RID: 6418 RVA: 0x00096273 File Offset: 0x00094473
		// (set) Token: 0x06001913 RID: 6419 RVA: 0x0009627B File Offset: 0x0009447B
		public string ParentAssemblyId
		{
			get
			{
				return this.mvid;
			}
			set
			{
				this.mvid = value;
			}
		}

		/// <summary>Gets or sets the assembly's version number.</summary>
		/// <returns>The version of the assembly.</returns>
		// Token: 0x17000581 RID: 1409
		// (get) Token: 0x06001914 RID: 6420 RVA: 0x00096284 File Offset: 0x00094484
		// (set) Token: 0x06001915 RID: 6421 RVA: 0x0009628C File Offset: 0x0009448C
		public string Version
		{
			get
			{
				return this.serializerVersion;
			}
			set
			{
				this.serializerVersion = value;
			}
		}

		/// <summary>Gets or sets the common language runtime (CLR) namespace of the assembly.</summary>
		/// <returns>A <see cref="T:System.String" /> containing the common language runtime (CLR) namespace of the assembly.</returns>
		// Token: 0x17000582 RID: 1410
		// (get) Token: 0x06001916 RID: 6422 RVA: 0x00096295 File Offset: 0x00094495
		// (set) Token: 0x06001917 RID: 6423 RVA: 0x0009629D File Offset: 0x0009449D
		public string Namespace
		{
			get
			{
				return this.ns;
			}
			set
			{
				this.ns = value;
			}
		}

		/// <summary>Gets or sets the type that the serializer operates on.</summary>
		/// <returns>The <see cref="T:System.Type" /> to be serialized.</returns>
		// Token: 0x17000583 RID: 1411
		// (get) Token: 0x06001918 RID: 6424 RVA: 0x000962A6 File Offset: 0x000944A6
		// (set) Token: 0x06001919 RID: 6425 RVA: 0x000962AE File Offset: 0x000944AE
		public Type Type
		{
			get
			{
				return this.type;
			}
			set
			{
				this.type = value;
			}
		}

		// Token: 0x04000A9F RID: 2719
		private string mvid;

		// Token: 0x04000AA0 RID: 2720
		private string serializerVersion;

		// Token: 0x04000AA1 RID: 2721
		private string ns;

		// Token: 0x04000AA2 RID: 2722
		private Type type;
	}
}
