using System;

namespace System.Xml.Serialization
{
	/// <summary>Indicates to the <see cref="T:System.Xml.Serialization.XmlSerializer" /> that the member must be treated as XML text when the class that contains it is serialized or deserialized.</summary>
	// Token: 0x020001E5 RID: 485
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue)]
	public class XmlTextAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlTextAttribute" /> class.</summary>
		// Token: 0x0600191A RID: 6426 RVA: 0x0005995F File Offset: 0x00057B5F
		public XmlTextAttribute()
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlTextAttribute" /> class.</summary>
		/// <param name="type">The <see cref="T:System.Type" /> of the member to be serialized. </param>
		// Token: 0x0600191B RID: 6427 RVA: 0x000962B7 File Offset: 0x000944B7
		public XmlTextAttribute(Type type)
		{
			this.type = type;
		}

		/// <summary>Gets or sets the type of the member.</summary>
		/// <returns>The <see cref="T:System.Type" /> of the member.</returns>
		// Token: 0x17000584 RID: 1412
		// (get) Token: 0x0600191C RID: 6428 RVA: 0x000962C6 File Offset: 0x000944C6
		// (set) Token: 0x0600191D RID: 6429 RVA: 0x000962CE File Offset: 0x000944CE
		public Type Type
		{
			get
			{
				return this.type;
			}
			set
			{
				this.type = value;
			}
		}

		/// <summary>Gets or sets the XML Schema definition language (XSD) data type of the text generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>An XML Schema (XSD) data type, as defined by the World Wide Web Consortium (www.w3.org) document "XML Schema Part 2: Datatypes".</returns>
		/// <exception cref="T:System.Exception">The XML Schema data type you have specified cannot be mapped to the .NET data type. </exception>
		/// <exception cref="T:System.InvalidOperationException">The XML Schema data type you have specified is invalid for the property and cannot be converted to the member type. </exception>
		// Token: 0x17000585 RID: 1413
		// (get) Token: 0x0600191E RID: 6430 RVA: 0x000962D7 File Offset: 0x000944D7
		// (set) Token: 0x0600191F RID: 6431 RVA: 0x000962ED File Offset: 0x000944ED
		public string DataType
		{
			get
			{
				if (this.dataType != null)
				{
					return this.dataType;
				}
				return string.Empty;
			}
			set
			{
				this.dataType = value;
			}
		}

		// Token: 0x04000AA3 RID: 2723
		private Type type;

		// Token: 0x04000AA4 RID: 2724
		private string dataType;
	}
}
